import { CSSProperties } from "react";

const S: Record<string, CSSProperties> = {
  input: {
    width: "100%",
    padding: "8px 10px",
    borderRadius: 4,
    border: "1px solid #ccc",
    background: "#fff",
    color: "#333",
    fontSize: 14,
    boxSizing: "border-box",
    marginBottom: 12,
  },
  btnPrimary: {
    padding: "8px 18px",
    borderRadius: 4,
    border: "none",
    background: "#3b82f6",
    color: "#fff",
    fontWeight: 600,
    cursor: "pointer",
    fontSize: 14,
  },
  btnDanger: {
    padding: "5px 12px",
    borderRadius: 4,
    border: "none",
    background: "#ef4444",
    color: "#fff",
    fontWeight: 600,
    cursor: "pointer",
    fontSize: 13,
  },
  btnEdit: {
    padding: "5px 12px",
    borderRadius: 4,
    border: "none",
    background: "#f59e0b",
    color: "#fff",
    fontWeight: 600,
    cursor: "pointer",
    fontSize: 13,
    marginRight: 6,
  },
  btnAdd: {
    padding: "8px 16px",
    borderRadius: 4,
    border: "none",
    background: "#22c55e",
    color: "#fff",
    fontWeight: 600,
    cursor: "pointer",
    fontSize: 14,
    marginBottom: 16,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    border: "1px solid #ddd",
  },
  th: {
    textAlign: "left",
    padding: "10px 14px",
    background: "#f1f5f9",
    color: "#333",
    fontWeight: 700,
    fontSize: 13,
    borderBottom: "2px solid #ddd",
    border: "1px solid #ddd",
  },
  td: {
    padding: "10px 14px",
    color: "#333",
    fontSize: 14,
    borderBottom: "1px solid #ddd",
    border: "1px solid #ddd",
  },
};

export const badge = (active: boolean): CSSProperties => ({
  display: "inline-block",
  padding: "2px 10px",
  borderRadius: 4,
  background: active ? "#dcfce7" : "#fee2e2",
  color: active ? "#166534" : "#991b1b",
  fontSize: 12,
  fontWeight: 600,
  border: `1px solid ${active ? "#86efac" : "#fca5a5"}`,
});

export default S;
